# Generated by Django 5.1.6 on 2025-02-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UomType',
            fields=[
                ('uomTypeId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hasTable', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=50)),
                ('parentTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModels.uomtype')),
            ],
            options={
                'db_table': 'UomType',
            },
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('uomId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=10)),
                ('numericCode', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('uomTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralModels.uomtype')),
            ],
            options={
                'db_table': 'Uom',
            },
        ),
    ]
