# Generated by Django 5.1.6 on 2025-02-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralModels', '0002_uomtype_uom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enumeration',
            old_name='enum_type_id',
            new_name='enumTypeId',
        ),
    ]
