# Generated by Django 5.1.6 on 2025-02-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralModels', '0003_rename_enum_type_id_enumeration_enumtypeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enumeration',
            old_name='enum_code',
            new_name='enumCode',
        ),
    ]
