# Generated by Django 5.1.6 on 2025-02-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralModels', '0004_rename_enum_code_enumeration_enumcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enumeration',
            old_name='sequence_num',
            new_name='sequenceId',
        ),
    ]
